minerals_info = [
    {
        "name": "Fosfor",
        "info": "Fosfor samverkar med kalcium vid bildning och stärkning av ben och tänder. Det är även viktigt för syra-bas balansen i kroppen och för energiproduktion till kroppens alla energikrävande funktioner. Den största mängden finns lagrad i skelettet.",
        "info1": "Fosfor, som fosfat, finns framförallt i proteinrika livsmedel såsom mejeriprodukter, kött, fisk, fullkornsspannmål och baljväxter.",
        "info2": "Tillsatsen fosfor, eller fosfater får användas i många olika livsmedel. Fosfor är ett grundämne och framställs ur naturligt förekommande mineraler. I maten och i kroppen förekommer fosfor som olika fosfatföreningar. Som tillsats förekommer fosfor ofta i kombination med exempelvis natrium och kalium och bildar då salter som kallas fosfater.",
        "info3": "Har man brist på fosfor kan det leda till urkalkning av skelettet, försämrad njurfunktion och nerv- och muskelproblem. Det är dock mycket ovanligt med brist på fosfor. För högt intag kan leda till skador på njurarna och påverkan på skelettet så att kalcium läcker ut vilket i sin tur leder till problem med blodcirkulationen. Den övre gränsen för säkert intag är satt till 3000 mg per dag för vuxna.",
        "info4": "Tillräckligt intag för fosfor baseras på Rekommenderat intag för kalcium. Det tillräckliga intaget skiljer sig mellan olika åldersgrupper.",
    },
    {
        "name": "Jod",
        "info": "Jod ingår i sköldkörtelhormoner som deltar i ämnesomsättningen. Jod förekommer naturligt i berggrunden och halterna varierar mycket mellan olika geografiska områden.",
        "info1": "Vi får i oss jod från livsmedel såsom fisk, skaldjur, ägg och mejeriprodukter. Även joderat koksalt är en viktig källa till jod. Vissa algprodukter som säljs som näringstillskott innehåller mycket jod, dock kan det skilja mycket beroende på preparat.",
        "info2":"Jodbrist leder till struma, förstoring av sköldkörteln. För gravida och ammande är det extra viktigt att få i sig tillräckligt med jod då jodbrist under fosterstadiet kan leda till störningar i utvecklingen av nervsystemet, den fysiska utvecklingen samt leda till psykiska utvecklingsstörningar. I Sverige är jodbrist inte vanligt förekommande sedan man införde jodberikning av hushållssalt. Globalt är jodbrist fortfarande ett problem i många länder.",
        "info3": "För högt intag av jod kan påverka sköldkörtelns funktion och leda till rubbningar i sköldkörtelhormonbalansen. En övre gräns för säkert intag är 600 mikrogram per dag för vuxna. För gravida och ammande kan jodöverskott påverka fostrets mentala och fysiska utveckling vid för högt intag, utan att det påverkar modern.",
    },
    {
        "name": "Järn",
        "info": "Järn ingår i hemoglobin som transporterar syre i blodet och i myoglobin som finns i musklerna. Järn ingår även i en del enzymer.",
        "info1":"Järn finns främst i inälvs- och blodmat, men finns även i kött, ägg och skaldjur samt i vegetabiliska livsmedel som fullkornsprodukter, nötter, frön, torkad frukt och baljväxter.",
        "info2":"Jämfört med många andra näringsämnen är kroppens upptag av järn lågt. Det finns två olika typer av järn, hemjärn och icke-hemjärn. Hemjärn är lättast för kroppen att tillgodogöra sig och utgör ungefär hälften av järninnehållet i kött och blodmat. Vegetabiliska livsmedel innehåller uteslutande icke-hemjärn som inte tas upp lika effektivt och i större grad påverkas av andra ämnen. Vitamin C, fisk och kött kan exempelvis förbättra upptaget av icke-hemjärn medan ämnen som polyfenoler (som finns i exempelvis te, kaffe och vin) och fytinsyra (finns i fiberrika livsmedel som spannmål, baljväxter och nötter) kan minska upptaget. Även ett högt intag av kalcium kan verka hämmande på järnupptaget.",
        "info3": "En person med järnbrist tar upp mer järn från kosten än en person vars järndepåer är fyllda. Järntillgängligheten är speciellt viktig under perioder där järndepåerna byggs upp, exempelvis hos spädbarn.Järnbrist kan uppstå om man inte får i sig tillräckligt med järn från maten för att ersätta det som kroppen förlorar vid bland annat blodförluster. Till slut kan man då få blodbrist, järnbristanemi. Det finns då inte tillräckligt med järn för att bilda hemoglobin. Symtom vid detta tillstånd är blekhet, trötthet, andfåddhet och nedsatt immunförsvar. Järnbrist drabbar oftare gravida kvinnor, tonåringar eller kvinnor som förlorar mycket järn på grund av stora menstruationsblödningar. Av alla mikronäringsämnen är järnbristanemi vanligast globalt sett.",
        "info4":"Järn i större mängder kan vara giftigt. Tidiga symtom kan vara magont, kräkningar och diarré. Mycket höga doser av järn kan vara dödligt giftigt, speciellt för barn.",
    },
    {
        "name": "Kalcium",
        "info": "Kalcium är ett livsnödvändigt grundämne och behövs bland annat då skelett och tänder bildas samt vid blodkoagulering och för nervfunktion.",
        "info1":"Kalcium finns i de flesta livsmedel. Allra mest i mjölkprodukter, bladgrönsaker och nötter. Vegetabiliska alternativ till mjölk är ofta berikade med kalcium.",
        "info2":"Långvarig kalciumbrist kan orsaka benskörhet. Hos barn kan det leda till tillväxthämning.",
        "info3":"Kalcium kan överdoseras genom intag av kosttillskott vilket i kombination med högt intag av vitamin D kan leda till hyperkalcemi, förkalkning av kroppens vävnader, njursten och njurskador. Övre gräns för säkert intag av kalcium för vuxna är satt till 2500 mg per dag.",
        "info4":"Den mänskliga kroppen består av ca 1-2 procent kalcium och 99 procent av allt kalcium finns bundet i ben och tänder. Det fria kalciumet spelar roll för en rad processer i och mellan kroppens celler. Därför är koncentrationen av kalcium i blodet strikt reglerat genom ett samspel mellan tarmarna, njurarna och skelett. Bland annat regleras koncentrationen av parathormon och vitamin D3.",
    },
    {
        "name": "Kalium",
        "info": "Kalium är ett livsnödvändigt grundämne och behövs för kroppens nerv- och muskelfunktion samt för att reglera blodtrycket.",
        "info1":"Kalium finns i princip i alla livsmedel. Lite högre halter finns i nötter, frön, torkad frukt, potatis, färska frukter och grönsaker. Men även animaliska livsmedel som kött, fisk och mejeriprodukter är viktiga källor till kalium.",
        "info2":"Kaliumbrist är mycket ovanligt men kan uppstå exempelvis vid långvariga diaréer eller användande av vätskedrivande läkemedel. Kaliumbrist leder till trötthet, muskelsvaghet och rubbningar av hjärtrytmen. Det kan även leda till depression och förvirring.",
        "info3":"Ett långvarigt högt intag av kalium kan påverka hjärtfunktionen hos individer med nedsatt njurfunktion. Kosttillskott kan bidra till ett för högt intag vilket kan leda till hyperkalemi vilket är ett livsfarligt tillstånd som orsakar rubbningar i hjärtrytmen vilket i sin tur kan utgöra en risk för hjärtstillestånd.",
    },
    {
        "name": "Magnesium",
        "info": "Magnesium behövs bland annat för produktionen av protein, för omsättningen av kalcium samt för normal nerv- och muskelfunktion.",
        "info1":"Magnesium finns främst i baljväxter, bladgrönsaker, fullkornsprodukter och kött, fisk och skaldjur. Det finns även i dricksvatten, framförallt om det är hårt vatten.",
        "info2":"Magnesiumbrist är ytterst ovanligt men kan uppstå vid kostrestriktion eller vid vissa sjukdomar. Det kan ge hämmad tillväxt, beteendestörningar och störningar i hjärtfunktionen. Allvarlig magnesiumbrist kan ge kramp.",
        "info3":"Ett högt intag av magnesium från kosttillskott kan ge diarré. Därför har en övre gräns för säkert intag satt till 250 mg per dag.",
    },
    {
        "name": "Natrium",
        "info": "Natrium är ett nödvändigt grundämne i kroppen och finns i kroppsvätskan utanför cellerna men även i skelettet. Natrium är viktigt för syra-basbalansen samt vatten- och saltbalansen i kroppen. Balansen mellan natrium och kalium påverkar blodtrycket. Natrium behövs även för nervernas normala funktion och för upptaget av glukos och vissa aminosyror.",
        "info1":"Vi får främst i oss natrium via salt och andra typer av bordssalt och havssalt. Natrium finns även naturligt förekommande i livsmedel som kött, fisk och spannmål.",
        "info2":"Natriumbrist är mycket ovanligt men akut brist kan uppstå vid extrema tillfällen som exempelvis långvarig magsjuka eller stark svettning.",
        "info3":"För mycket natrium kan vara orsak till högt blodtryck vilket i sin tur bidrar till att öka risken för hjärtinfarkt, hjärtsvikt, stroke och skador på njurarna. ",
        "info4":"Enligt de Nordiska Näringsrekommendationerna bör intaget av salt minska hos de flesta vuxna i befolkningen och natriumintaget bör max vara 2,3 g/dag vilket motsvarar 5,75 g salt per dag. Begränsas intaget till detta förväntas risken för kronisk sjukdom såsom högt blodtryck och hjärt- och kärlsjukdomar minska i befolkningen. Saltintag hos barn bör också begränsas och för barn 2-10 år bör det ligga på runt 3-4 g salt per dag. Maxintag av natrium varierar med ålder.",
    },
    {
        "name": "Selen",
        "info": "Selen ingår i enzym som skyddar cellerna mot oxidation, samverkar med vitamin E och deltar i immunologiska försvarsmekanismer.",
        "info1":"Selen är ett grundämne som finns i jorden och finns i nästan all mat även om halterna varierar. I Sverige är marken selenfattig och vegetabilier odlade i Sverige har därför låga halter. De livsmedel som innehåller mest selen är fisk, skaldjur, inälvsmat, nötter/fröer, linser, ägg och ost. Vuxna får i sig ungefär 40 till 50 mikrogram selen per dag. ",
        "info2":"Allvarlig brist på selen kan leda till hjärtmuskelförändringar, men selenbrist är ovanligt. Det finns även studier som visar att det kan vara förknippat med vissa cancerformer, dock saknas kliniska studier i västvärlden för att bekräfta detta.",
        "info3":"Selen i högre doser är giftigt. Ett för högt selenintag kan påverka mag- och tarmkanalen samt försämra tillväxt av hår och naglar. Dagsintaget bör inte överskrida 255 mikrogram.",
    },
    {
        "name": "Zink",
        "info": "Zink är ett livsnödvändigt mineral. Det ingår i 100-talet enzymer i kroppen som påverkar omsättning av proteiner, kolhydrater, fett, nukleinsyror och vissa vitaminer som exempelvis vitamin A. Zink behövs även för immunsystemet.",
        "info1":"Zink finns i kött, mejeriprodukter, fullkornsprodukter och inälvsmat. Upptag av zink underlättas av animaliska proteiner. Även musslor, ost och nötter är rika på zink.",
        "info2":"Det rekommenderade intaget av zink varierar med kön och ålder och rekommendationerna gäller för en blandad animalisk-vegetabilisk kost. De som äter strikt vegetarisk och cerealiebasera kost rekommenderas ett intag som är 25-30% högre.",
        "info3":"Zinkbrist är ovanligt i Sverige. Brist på zink hos barn ger tillväxthämning och störd utveckling. Brist hos vuxna ger hudförändringar, försämrad sårläkning och försämrad aptit.",
        "info4":"Europeiska Livsmedelssäkerhets-myndigheten har fastställt en övre gräns för säkert intag för vuxna till 25 mg zink per dag.",
    },
]