from flask_sqlalchemy import SQLAlchemy

db=SQLAlchemy()

class Fruit (db.Model):
    __tablename__='Fruit'
    Namn=db.Column(db.String, primary_key=True)
    Energi_kcal= db.Column(db.Integer)
    Energi_KJ = db.Column(db.Integer)
    Fett_g = db.Column(db.Float)
    Protein_g = db.Column(db.Float)
    Kolhydrater_g =db.Column(db.Float)
    Fibrer_g =db.Column(db.Float)
    Vatten_g = db.Column(db.Float)
    Sockerarter_g =db.Column(db.Float)
    Tiamin_mg =db.Column(db.Float)
    Riboflavin_mg =db.Column(db.Float)
    Niacin_mg =db.Column(db.Float)
    Niacinekvivalenter_NE_per_mg =db.Column(db.Float)
    Vitamin_B6_mg = db.Column(db.Float)
    Folat_mikrog = db.Column(db.Float)
    Vitamin_B12_mikrog =db.Column(db.Integer)
    Vitamin_C_mg = db.Column(db.Float)
    Vitamin_A_RE_per_mikrog =db.Column(db.Float)
    Retinol_mikrog =db.Column(db.Integer)
    Betakaroten_mikrog = db.Column(db.Integer)
    Vitamin_D_mikrog =db.Column(db.Float)
    Vitamin_E_mg = db.Column(db.Float)
    Vitamin_K_mikrog = db.Column(db.Float)
    Fosfor_mg =db.Column(db.Integer)
    Jod_mikrog = db.Column(db.Float)
    Järn_mg = db.Column(db.Float)
    Kalcium_mg = db.Column(db.Integer)
    Kalium_mg = db.Column(db.Integer)
    Magnesium_mg = db.Column(db.Integer)
    Natrium_mg = db.Column(db.Integer)
    Salt_g = db.Column(db.Float)
    Selen_mikrog = db.Column(db.Float)
    Zink_mg = db.Column(db.Float)