vitamins_info = [
    {
        "name": "Vitamin A",
        "info":"A-vitamin behövs för att syn, hud och slemhinnor ska fungera normalt. Den har även en grundläggande betydelse för utveckling, tillväxt och differentiering av embryot under den tidiga delen av graviditeten för att fostret ska utvecklas normalt och få en fullgod syn. ",
        "info1":"A-vitamin finns i olika former; Färdigbildat A-vitamin (retinol och retinylestrar) som finns i animaliska livsmedel, exempelvis inälvsmat, matfett, ost och ägg. Provitamin A som är ett förstadium till A-vitamin i form av karotenoider finns främst i växtbaserade livsmedel som grönsaker och rotfrukter. Karotenoider kan omvandlas till A-vitamin i kroppen när det behövs. Betakaroten är den vanligaste men även alfakaroten och betakrytoxantin kan omvandlas till A-vitamin.",
        "info2":"Att äta varierat täcker dagsbehovet väl och brist på A-vitamin förekommer i princip inte i Sverige idag. Globalt är dock A-vitaminbrist ett problem. Lindrig brist kan ge nattblindhet, vilket kan leda till blindhet om det fortgår och A-vitaminbrist är den enskilt största orsaken till blindhet i världen. Brist på A-vitamin under en graviditet kan ge allvarliga skador på fostret. Allvarlig brist ger nedsatt motståndskraft mot infektioner.",
        "info3":"A-vitamin i stora doser är skadligt, framförallt den färdigbildade formen som retinol. Det är främst genom kosttillskott man får i sig för stora mängder. Äter man mycket lever under lång tid kan även det ge överdosering av A-vitamin. Risken för överdosering av A-vitamin genom konsumtion av karotenoider är mindre eftersom omvandlingen av karotenoider till retinol minskar i takt med att intaget ökar.",
        "info4":"Den allvarligaste effekten av för högt intag av retinol är fosterskador. Gravida bör inte äta mer än 1000 mikrogram A-vitamin i form av retinol per dag som tillskott om inte annat ordinerats av läkare. A-vitamintillskott av karotenoider innebär alltså inte samma risk.",
        "info5": "Nordiska näringsrekommendationer anger en övre gräns för intag av retinol i kosttillskott om 3000 mikrogram per dag för vuxna. För kvinnor som passerat klimakteriet är den övre gränsen 1500 mikrogram per dag. Det är för att risken för benskörhet är högre hos kvinnor efter klimakteriet och det inte gått att utesluta att intag över 1500 mikrogram per dag ökar risken för frakturer.",
        "info6": "Hur mycket A-vitamin vi behöver uttrycks i retinolekvivalenter (det sammantagna innehållet av vitamin A i mat från både animaliska och vegetabiliska källor och motsvarar den biologiska aktiviteten i 1 mikrogram retinol) och det dagliga behovet varierar med kön och ålder."
    },
    {
        "name": "Vitamin C",
        "info":"C-vitamin fungerar som antioxidant och behövs bland annat för att bygga upp kroppens brosk- och benvävnad. Det underlättar även upptaget av järn från maten.",
        "info1": "C-vitamin får vi främst i oss från grönsaker, bär och citrusfrukter. C-vitamin är värmekänsligt och om mat hålls uppvärmd länge minskar mängden C-vitamin.",
        "info2": "Det är ovanligt med C-vitaminbrist i Sverige. Lindrig brist kan ge trötthet, svaghet och irritation. Allvarlig brist kan i sällsynta fall ge skörbjugg med symtom som inflammation i tandköttet, försämrad sårläkning och infektionskänslighet.",
        "info3": "Det finns inget som tyder på att höga intag, mer än 1000 mg per dag, riskerar att ge några allvarliga konsekvenser. Dock kan känsliga personer få diarré och möjligtvis njursten vid för högt intag.",
    },
    {
        "name": "Vitamin D",
        "info":"D-vitamin har många funktioner i kroppen. Bland annat behövs D-vitamin för att vi ska kunna bilda starka tänder och skelett. ",
        "info1":"D-vitamin är ett av få vitaminer vi riskerar att få för lite av. Därför rekommenderas tillskott av D-vitamin till vissa grupper. D-vitamin kan vi få i oss på två sätt, dels via maten och dels bildas D-vitamin i huden när vi är ute i solen. Fet fisk, exempelvis lax, sill och makrill, är det livsmedel som innehåller mest D-vitamin. I Sverige berikas även de flesta mjölkprodukter, växtdrycker, smörgåsfetter och matfettsblandningar med D-vitamin. Även kött och ägg innehåller D-vitamin. Under sommarhalvåret är sol på huden den viktigaste källan till D-vitamin för de flesta. Vitaminet lagras även i kroppen och det som bildas i solen på sommaren kan täcka en del av behovet under vinterhalvåret.",
        "info2":"Långvarig brist på D-vitamin kan orsaka rakit hos barn vilket visar sig som mjukt och missformat skelett. Hos vuxna kan långvarig D-vitaminbrist orsaka benuppmjukning, osteomalaci. Allvarlig brist på D-vitamin kan orsaka kramper. Detta är dock mycket ovanligt i Sverige. Det finns även forskning som tyder på att låga halter av D-vitamin kan ha betydelse för uppkomsten av andra sjukdomar såsom hjärt- och kärlsjukdom.",
        "info3":"För mycket D-vitamin i blodet kan vara farligt. Det går inte att få i sig för höga doser via maten, men om du tar kosttillskott kan du få i dig för mycket. De övre gränserna per dag är för barn, 1-10 år, 50 mikrogram och för vuxna och barn över 11 år 100 mikrogram. För stora mängder D-vitamin kan leda till att man får för mycket kalcium i blodet, kalciuminlagring i njurarna och njursvikt.",
    },
        {
        "name": "Vitamin E",
        "info":"E-vitamin är en antioxidant som bland annat skyddar våra vävnader genom att förhindra att de fleromättade fettsyrorna som bygger upp membranen bryts ner.",
        "info1":"Vi får i oss E-vitamin främst från frön, nötter, vegetabiliska oljor, margarin, vetegroddar, gröna bladväxter, avokado, fullkornsprodukter och ägg.",
        "info2":"Den form av E-vitamin som är nödvändig för kroppens funktioner är alfa-tokoferol och är det som anges i tabellen.",
        "info3":"Brist på E-vitamin har inte påvisats hos friska personer men kan uppstå hos personer med kroniskt nedsatt absorption av fett och i vissa fall hos för tidigt födda barn.",
        "info4": "E-vitamin i naturlig form har låg giftighet eftersom kroppen har en effektiv kontroll av hur vitaminet omsätts och lagras i kroppen. För högt intag av E-vitamin i form av kosttillskott kan dock ha negativa hälsoeffekter, bland annat ökad dödlighet, men några definitiva slutsatser kan inte dras baserat på de studier som finns tillgängliga idag. Sammantaget pekar forskningen på att ett högt intag av E-vitamin under lång tid inte ger några hälsofördelar i den allmänna befolkningen. Den europeiska myndigheten för livsmedelssäkerhet har satt en övre gräns för intag av E-vitamin från kosttillskott till 300 mg per dag för vuxna.",
    },
        {
        "name": "Folat",
        "info":"Folat behövs för att bilda nya celler och röda blodkroppar. När cellbildningen ökar, exempelvis då man växer eller är gravid ökar behovet av folat.",
        "info1":"Folat finns i nästan all mat i mycket små mängder. Folat och folsyra är olika former av samma B-vitamin. Folat finns naturligt i mat medan folsyra är ett konstgjort framställt folat som används vid berikning och i kosttillskott. Mörkgröna bladgrönsaker och olika slag av kål, bönor, kikärtor, linser, frukt och bär är livsmedel som innehåller mycket folat. Även fullkornsprodukter, filmjölk och yoghurt innehåller förhållandevis mycket folat.",
        "info2":"Brist på folat/folsyra ger blodbrist, anemi, eftersom kroppen inte kan tillverka röda blodkroppar på rätt sätt. Många får idag i sig för lite folat från maten. Om mamman har för låga halter folat i blodet före och under första veckorna i graviditeten ökar risken för ryggmärgsbråck hos fostret. Låga folathalter ökar även risken för missfall.",
        "info3":"Det finns ingen risk att få i sig för mycket folat genom att äta mycket folatrik mat. Däremot kan högt intag av folsyra via tillskott maskera symtom som uppkommer av vitamin B12-brist. Den europeiska livsmedelssäkerhets-myndigheten har därför satt en övre gräns för intag av folsyra till 1000 mikrogram per dag för vuxna.",
    },
            {
        "name": "Vitamin K",
        "info":"K-vitamin är nödvändigt för blodets koagulering och har även betydelse för bentätheten.",
        "info1":"Vi får i oss K1-vitamin, fyllokinon, från kål, gröna bladgrönsaker och vissa oljor. Kött, lever, äggula och mejeriprodukter innehåller högre halter av vitamin K2, menakinoner. Vitamin K2 bildas av bakterier i mag-tarmkanalen hos djur men kan även finnas i högre halter i fermenterade livsmedel och alger. Vitamin K2 bildas av tarmbakterier även hos människor, dock inte i tillräcklig mängd för att tillgodose kroppens behov.",
        "info2":"Innehållet av K-vitamin i livsmedel påverkas av faktorer som sort, odlings- och lagringsförhållanden. Vitamin K1 är ljuskänsligt men relativt värmestabilt.",
        "info3":"Brist på K-vitamin är ytterst ovanligt, men har påvisats hos personer med nedsatt absorption från tarmen och vid antibiotikabehandling. Inlagringen av K-vitamin i kroppen är låg och nyfödda har inte heller utvecklat någon tarmflora som kan bilda vitaminet. För att motverka blödningar innanför skallbenet ges K-vitamin som injektion till alla nyfödda i Sverige.",
        "info4":"Det finns inget belägg för att högt intag av K-vitamin från kosten skulle ha negativa effekter på hälsan.",
    },
            {
        "name": "Niacin",
        "info":"Niacin som är ett B-vitamin, behövs för att bryta ner fett, kolhydrater och protein. Det hjälper till att hålla nervsystemet fungerande och huden frisk. Niacin finns i två former, nikotinsyra och nikotinamid, vilka båda förekommer naturligt i maten. ",
        "info1":"Höga halter niacin finns i kyckling, fisk, kött, jordnötter, hårt bröd och spannmål. Det finns även produkter berikade med niacin, exempelvis frukostflingor.",
        "info2":"Brist på niacin är mycket ovanligt i Sverige, men det kan förekomma vid extremt ensidig kosthållning. Allvarlig brist på nicacin ger hudsjukdomen pellagra.",
        "info3":"Det finns inga studier som tyder på att naturligt förekommande niacin i mat orsakar negativa hälsoeffekter. Däremot kan tillskott eller berikning orsaka reaktioner som plötslig hudrodnad vid doser på 30-1000 mg per dag. Detta är dosberoende och symtomen kännetecknas av brännande, hettande eller stickande känsla i ansiktet och på bröstet samt röd eller flammande hud. Normalt sett är reaktionen övergående och inte farlig för i övrigt friska personer. Ännu högre doser av niacin kan dock ge andra allvarliga biverkningar som leverpåverkan och magbesvär. En övre gräns för intag är satt för vuxna till 10 mg per dag av nikotinsyra och 900 mg per dag för nikotinamid.",
        "info4": "Det rekommenderade intaget av niacin anges som niacinekvivalenter per megajoule, dvs i relation till det totala energiintaget. Det rekommenderade intaget anges som niacinekvivalenter/MJ och är oberoende av kön och ålder satt till 1,6 niacinekvivalenter/MJ."
    },
            {
        "name": "Riboflavin",
        "info":"Riboflavin, tidigare kallad vitamin B2 behövs för nedbrytning av fett, kolhydrater och protein.",
        "info1":"Riboflavin finns i många livsmedel och bra källor är kött, fågel, ägg, inälvsmat, korv, mjölk och mjölkprodukter. Det finns även i vegetabiliska livsmedel som baljväxter, gröna bladgrönsaker och fullkornsprodukter. Vissa drycker berikas också med riboflavin, exempelvis havre-, soja- och risdryck (ej ekologiska).",
        "info2":"Brist på riboflavin är ovanligt men kan ge slemhinne- och hudförändringar.",
        "info3":"Det finns inget som tyder på att riboflavin som intas via maten har några negativa hälsoeffekter. Idag saknas information för att kunna säga vilken nivå av riboflavin som eventuellt skulle kunna vara skadlig.",
    },
                {
        "name": "Tiamin",
        "info":"Tiamin, förr kallat vitamin B1, behövs för ämnesomsättningen av kolhydrater och protein.",
        "info1":"Vi får i oss tiamin via kosten och det finns i exempelvis frukostflingor och müsli, fläskkött, inälvsmat, vetegroddar, solrosfrön och bröd.",
        "info2":"Brist på tiamin är ovanligt i Sverige sett till hela befolkningen, men kan ofta ses vid alkoholmissbruk. Allvarlig brist ger sjukdomen beriberi.",
        "info3":"Det finns inget som tyder på att tiamin ger negativa hälsoeffekter vid intag via maten och intag av upp till 500 mg per dag över flera veckor har inte kunnat kopplas till negativa effekter.",
        "info4":"Det rekommenderade dagliga behovet varierar med kön och ålder. I nordiska näringsrekommendationerna 2023 anges det rekommenderade intaget av tiamin som milligram per megajoule, dvs relation till det totala energiintaget. För alla oberoende av ålder så är det rekommenderade intaget satt till 0,1 milligram/MJ.",
    },
                {
        "name": "Vitamin B6",
        "info":"Vitamin B6, även kallat pyridoxin, är nödvändigt för proteinomsättningen och har betydelse för exempelvis nervernas funktion.",
        "info1":"Högst halter av vitamin B6 finns i animaliska livsmedel som kött, fågel, korv, ägg och mjölkprodukter. Det finns dock även i potatis, spannmål, bär och matbröd, vilka också är goda källor till vitamin B6. Frukostflingor av fullkorn, fullkornsbröd, baljväxter, gröna bladgrönsaker, frukt, mandel, vetegroddar och sesamfrön innehåller också vitamin B6.",
        "info2":"Brist på vitamin B6 är mycket ovanligt då vitamin B6 finns i nästan allt vi äter. Symptom på brist är hudförändringar kring mun, näsa och ögon, kramper och anemi.",
        "info3":"Ett högt intag av vitamin B6 under lång tid, månader eller år, kan vara skadligt. Den europeiska myndigheten för livsmedelssäkerhet har satt en övre gräns för intag av vitamin B6 till 12 mg per dag för vuxna.",
    },
                {
        "name": "Vitamin B12",
        "info":"Vitamin B12, även kallat kobalamin, behövs bland annat för cellernas ämnesomsättning och för bildning av blodkroppar. Det är också nödvändigt för nervsystemets funktion.",
        "info1":"Vitamin B12 finns främst i animaliska livsmedel som fisk, kött, skaldjur, ägg, lever, mjölk och ost. Fermenterade produkter kan också innehålla lite vitamin B12. Det finns även inaktiva former av vitamin B12 i kosten, speciellt i vegetabilier. De inaktiva formerna av vitaminet kan våra kroppar inte tillgodogöra sig.",
        "info2":"Är man vegan är det mycket viktigt med tillskott på vitamin B12 eller tillräckliga mängder av berikade livsmedel. Även för lakto-ovo-vegetarianer kan intaget bli för lågt, trots att vitamin B12 finns i både mjölkprodukter och ägg. Vissa drycker berikas med vitamin B12, ex havre- soja- och risdryck (ej ekologisk).",
        "info3":"Förmågan att ta upp vitamin B12 minskar med åldern och därför kan en del äldre personer få brist på vitaminet, även när de äter vanlig mat som innehåller B12. Även vissa sjukdomstillstånd kan bidra till brist på vitamin B12. En sådan sjukdom är perniciös anemi, en autoimmun sjukdom som innebär att patienten har svårt att ta upp vitamin B12 från tarmen. Allvarlig brist kan ge blodbrist, nervskador och försämrat minne.",
        "info4":"Det finns inget som tyder på att ett högt intag av vitamin B12 är skadligt. Intag på upp till 100 mikrogram per dag från maten eller genom kosttillskott har inte kunnat kopplas till negativa effekter.",
    },
]